version: "3"
services:
  migrator:
    build: 
      context: './'
    container_name: 'migrator'
    #command: "python3 /tmp/configure.py"
    command: "tail -f /dev/null"
    env_file:
      - .env
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      ADDITIONAL: $ADDITIONAL
    volumes:
      - ./:/mnt
